export const BLOODBATTLE_EVENT_TYPES = {
  gameStarted: "GameStarted",
  handDealt: "HandDealt",
  exchangeThreeSelected: "ExchangeThreeSelected",
  tilesReceived: "TilesReceived",
  exchangeCompleted: "ExchangeCompleted",
  lackChosen: "LackChosen",
  turnStarted: "TurnStarted",
  tileDrawn: "TileDrawn",
  tileDrawnPrivate: "TileDrawnPrivate",
  tileDiscarded: "TileDiscarded",
  tileDiscardedPrivate: "TileDiscardedPrivate",
  claimWindowOpened: "ClaimWindowOpened",
  claimResponded: "ClaimResponded",
  claimWindowResolved: "ClaimWindowResolved",
  pengMade: "PengMade",
  gangMade: "GangMade",
  huDeclared: "HuDeclared",
  settled: "Settled",
  gameEnded: "GameEnded",
  wallExhausted: "WallExhausted",
  gangReplacementDrawn: "GangReplacementDrawn",
} as const;
