export const JUNK_EVENT_TYPES = {
  gameStarted: "GameStarted",
  handDealt: "HandDealt",
  turnStarted: "TurnStarted",
  tileDrawn: "TileDrawn",
  tileDiscarded: "TileDiscarded",
  claimWindowOpened: "ClaimWindowOpened",
  claimResponded: "ClaimResponded",
  claimWindowResolved: "ClaimWindowResolved",
  legalActionsUpdated: "LegalActionsUpdated",
  chiMade: "ChiMade",
  pengMade: "PengMade",
  gangMade: "GangMade",
  gangReplacementDrawn: "GangReplacementDrawn",
  huDeclared: "HuDeclared",
  settled: "Settled",
  gameEnded: "GameEnded",
  wallExhausted: "WallExhausted",
} as const;
